spring.application.name=productServices

server.port = 8082
# =================== database configuration ====================
spring.datasource.url=jdbc:postgresql://localhost:5432/product_service_db
spring.datasource.username = postgres
spring.datasource.password = Yashwanth@13
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql=true


# =============== eureka configuration =================
spring.client.service-url.defaultZone = http://localhost:8761/eureka


# ================= image size configuration ==============
spring.servlet.multipart.max-request-size = 50MB
spring.servlet.multipart.max-file-size = 50MB